-- Spring Batch 5 PostgreSQL metadata schema.
-- 운영 재기동 때 같은 DDL이 반복되어도 실패하지 않도록 IF NOT EXISTS를 사용한다.

CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE (
	JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
	VERSION BIGINT,
	JOB_NAME VARCHAR(100) NOT NULL,
	JOB_KEY VARCHAR(32) NOT NULL,
	CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	VERSION BIGINT,
	JOB_INSTANCE_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL,
	END_TIME TIMESTAMP DEFAULT NULL,
	STATUS VARCHAR(10),
	EXIT_CODE VARCHAR(2500),
	EXIT_MESSAGE VARCHAR(2500),
	LAST_UPDATED TIMESTAMP,
	CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
		REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS (
	JOB_EXECUTION_ID BIGINT NOT NULL,
	PARAMETER_NAME VARCHAR(100) NOT NULL,
	PARAMETER_TYPE VARCHAR(100) NOT NULL,
	PARAMETER_VALUE VARCHAR(2500),
	IDENTIFYING CHAR(1) NOT NULL,
	CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
		REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	VERSION BIGINT NOT NULL,
	STEP_NAME VARCHAR(100) NOT NULL,
	JOB_EXECUTION_ID BIGINT NOT NULL,
	CREATE_TIME TIMESTAMP NOT NULL,
	START_TIME TIMESTAMP DEFAULT NULL,
	END_TIME TIMESTAMP DEFAULT NULL,
	STATUS VARCHAR(10),
	COMMIT_COUNT BIGINT,
	READ_COUNT BIGINT,
	FILTER_COUNT BIGINT,
	WRITE_COUNT BIGINT,
	READ_SKIP_COUNT BIGINT,
	WRITE_SKIP_COUNT BIGINT,
	PROCESS_SKIP_COUNT BIGINT,
	ROLLBACK_COUNT BIGINT,
	EXIT_CODE VARCHAR(2500),
	EXIT_MESSAGE VARCHAR(2500),
	LAST_UPDATED TIMESTAMP,
	CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
		REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT (
	STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT,
	CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
		REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT (
	JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
	SHORT_CONTEXT VARCHAR(2500) NOT NULL,
	SERIALIZED_CONTEXT TEXT,
	CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
		REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
);

CREATE SEQUENCE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ MAXVALUE 9223372036854775807 NO CYCLE;
CREATE SEQUENCE IF NOT EXISTS BATCH_JOB_SEQ MAXVALUE 9223372036854775807 NO CYCLE;

CREATE TABLE IF NOT EXISTS data_collection_runs (
	run_id VARCHAR(80) NOT NULL PRIMARY KEY,
	source VARCHAR(40) NOT NULL,
	status VARCHAR(20) NOT NULL,
	requested_by VARCHAR(120) NOT NULL,
	started_at TIMESTAMP NOT NULL,
	completed_at TIMESTAMP,
	collected_count INTEGER NOT NULL,
	failure_message VARCHAR(1000)
);

CREATE INDEX IF NOT EXISTS idx_data_collection_runs_started_at
	ON data_collection_runs (started_at DESC);

CREATE TABLE IF NOT EXISTS mobility_profiles (
	user_id VARCHAR(120) NOT NULL PRIMARY KEY,
	mobility_type VARCHAR(40) NOT NULL,
	avoid_stairs BOOLEAN NOT NULL,
	require_elevator BOOLEAN NOT NULL,
	allow_escalator BOOLEAN NOT NULL,
	minimize_transfers BOOLEAN NOT NULL,
	avoid_long_walks BOOLEAN NOT NULL,
	large_text BOOLEAN NOT NULL,
	high_contrast BOOLEAN NOT NULL,
	simple_view BOOLEAN NOT NULL,
	updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_mobility_profiles_updated_at
	ON mobility_profiles (updated_at DESC);

CREATE TABLE IF NOT EXISTS favorite_stations (
	user_id VARCHAR(120) NOT NULL,
	station_id VARCHAR(120) NOT NULL,
	added_at TIMESTAMP NOT NULL,
	PRIMARY KEY (user_id, station_id)
);

CREATE INDEX IF NOT EXISTS idx_favorite_stations_station_user
	ON favorite_stations (station_id, user_id);

CREATE INDEX IF NOT EXISTS idx_favorite_stations_user_added
	ON favorite_stations (user_id, added_at ASC, station_id ASC);

CREATE TABLE IF NOT EXISTS favorite_facilities (
	user_id VARCHAR(120) NOT NULL,
	facility_id VARCHAR(120) NOT NULL,
	added_at TIMESTAMP NOT NULL,
	PRIMARY KEY (user_id, facility_id)
);

CREATE INDEX IF NOT EXISTS idx_favorite_facilities_facility_user
	ON favorite_facilities (facility_id, user_id);

CREATE INDEX IF NOT EXISTS idx_favorite_facilities_user_added
	ON favorite_facilities (user_id, added_at ASC, facility_id ASC);
