ALTER TABLE admin_role_permissions DROP CONSTRAINT admin_role_permissions_permission_code_check;

ALTER TABLE admin_role_permissions ADD CONSTRAINT admin_role_permissions_permission_code_check
    CHECK (permission_code IN ('admin.view', 'admin.report.review', 'admin.master.edit', 'admin.field.operate', 'admin.data.operate', 'admin.security.audit', 'admin.security.admin', 'admin.audit.read', 'admin.privacy-log.read'));

CREATE TABLE admin_audit_events (
    audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(40) NOT NULL CHECK (event_type IN ('LOGIN', 'LOGIN_FAILURE', 'LOGOUT', 'ADMIN_ACTION', 'PRIVACY_READ', 'SYSTEM_CHANGE', 'BATCH_OPERATION', 'MASTER_DATA_CHANGE')),
    actor VARCHAR(120) NOT NULL,
    role_permission VARCHAR(1000),
    request_id VARCHAR(120),
    client_ip VARCHAR(120),
    user_agent VARCHAR(300),
    target_type VARCHAR(120) NOT NULL,
    target_id VARCHAR(160),
    action VARCHAR(160) NOT NULL,
    outcome VARCHAR(40) NOT NULL CHECK (outcome IN ('SUCCESS', 'FAILURE')),
    reason VARCHAR(500),
    occurred_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_admin_audit_events_occurred_at
    ON admin_audit_events (occurred_at);

CREATE INDEX idx_admin_audit_events_type_occurred_at
    ON admin_audit_events (event_type, occurred_at);

INSERT INTO admin_role_permissions (role_code, permission_code, created_at)
VALUES
    ('SECURITY_ADMIN', 'admin.audit.read', CURRENT_TIMESTAMP),
    ('SECURITY_ADMIN', 'admin.privacy-log.read', CURRENT_TIMESTAMP),
    ('SUPER_ADMIN', 'admin.audit.read', CURRENT_TIMESTAMP),
    ('SUPER_ADMIN', 'admin.privacy-log.read', CURRENT_TIMESTAMP);

INSERT INTO admin_menu_items (program_code, parent_program_code, display_name, display_order, hidden)
VALUES
    ('a-audits', NULL, '관리자 감사', 140, FALSE),
    ('a-privacy-audits', NULL, '개인정보 조회 로그', 150, FALSE);
