CREATE TABLE IF NOT EXISTS transit_master_overrides (
	entity_type VARCHAR(80) NOT NULL,
	entity_id VARCHAR(160) NOT NULL,
	payload_json TEXT NOT NULL,
	updated_by VARCHAR(120) NOT NULL,
	updated_at TIMESTAMP NOT NULL,
	PRIMARY KEY (entity_type, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_transit_master_overrides_updated
	ON transit_master_overrides (updated_at DESC, entity_type ASC, entity_id ASC);

CREATE TABLE IF NOT EXISTS transit_master_override_audits (
	audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	entity_type VARCHAR(80) NOT NULL,
	entity_id VARCHAR(160) NOT NULL,
	action VARCHAR(20) NOT NULL,
	updated_by VARCHAR(120) NOT NULL,
	previous_payload_json TEXT,
	payload_json TEXT,
	updated_at TIMESTAMP NOT NULL,
	CONSTRAINT chk_transit_master_override_action
		CHECK (action IN ('UPSERT', 'ROLLBACK'))
);

CREATE INDEX IF NOT EXISTS idx_transit_master_override_audits_target
	ON transit_master_override_audits (entity_type, entity_id, audit_id DESC);
