spring:
  application:
    name: easysubway-backend
  profiles:
    default: dev
  batch:
    job:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
