package com.easysubway.report.domain;

public enum FacilityReportType {
	BROKEN,
	UNDER_CONSTRUCTION,
	CLOSED,
	ROUTE_BLOCKED,
	ELEVATOR_UNAVAILABLE,
	STAIRS_PRESENT,
	ETA_INACCURATE,
	TRANSFER_IMPOSSIBLE,
	LOCATION_WRONG,
	INFORMATION_WRONG,
	RECOVERED
}
